django_bluzat/urls.py
from django.contrib import admin
from django.urls import path

from gestion_materiel import views
from gestion_materiel.views import accueil, liste_enseignants, ajout_enseignant, liste_salles, liste_accessoires, ajout_salle, liste_materiels

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accueil', accueil, name='accueil'),

    path('enseignants/liste_enseignants', liste_enseignants, name='liste_enseignants'),
    path('enseignants/ajout_enseignant', ajout_enseignant, name='ajout_enseignant'),
    path('enseignants/<int:enseignant_id>/supprimer', views.supprimer_enseignant, name='supprimer_enseignant'),
    path('enseignants/<int:enseignant_id>/materiels_possedes/', views.liste_materiels_possedes, name='liste_materiels_possedes'),
    path('enseignants/<int:enseignant_id>/materiels_proprietaire/', views.liste_materiels_proprietaire, name='liste_materiels_proprietaire'),

    path('salles/liste_salles', liste_salles, name='liste_salles'),
    path('liste_materiels_salle/<int:salle_id>/', views.liste_materiels_salle, name='liste_materiels_salle'),
    path('salles/ajout_salle', ajout_salle, name='ajout_salle'),
    path('salles/supprimer/<int:salle_id>/', views.supprimer_salle, name='supprimer_salle'),

    path('materiel/liste_materiels', liste_materiels, name='liste_materiels'),
    path('materiel/supprimer/<int:materiel_id>/', views.supprimer_materiel, name='supprimer_materiel'),
    path('materiel/ajout_materiel/', views.ajout_materiel, name='ajout_materiel'),

    path('materiel/<int:materiel_id>/accessoires/', liste_accessoires, name='liste_accessoires'),
    path('materiel/<int:materiel_id>/accessoires/supprimer/<int:accessoire_id>', views.supprimer_accessoire, name='supprimer_accessoire'),
    path('materiel/<int:materiel_id>/accessoires/ajouter/', views.ajouter_accessoire_via_materiel, name='ajouter_accessoire'),
    path('materiel/<int:materiel_id>/accessoire/<int:accessoire_id>/modifier/', views.modifier_accessoire, name='modifier_accessoire'),

    path('transfert/choix_materiel', views.choix_materiel, name='choix_materiel'),
    path('transfert/<int:materiel_id>/liste_historique_transferts/', views.liste_historique_transferts, name='liste_historique_transferts'),
    path('transfert/<int:materiel_id>/afficher_transfert/<int:transfert_id>/', views.afficher_transfert,name='afficher_transfert'),
    path('transfert/ajout_transfert/<int:materiel_id>/', views.ajout_transfert, name='ajout_transfert'),
    path('transfert/<int:materiel_id>/supprimer/<int:transfert_id>/', views.supprimer_transfert, name='supprimer_transfert'),
]

gestion_materiel/models.py
from django.db import models
from django.urls import reverse

class Enseignant(models.Model):
    nom = models.CharField(
        max_length=50,
        blank=False,
        null=True,
        default='aucun'
    )
    prenom = models.CharField(
        max_length=50,
        blank=False,
        null=True,
        default='aucun'
    )

    def __str__(self):
        return f"{self.nom} {self.prenom}"

class Salle(models.Model):
    nom = models.CharField(
        max_length=50,
        blank=False,
        null=True,
        default='aucun'
    )
    etage = models.CharField(
        max_length=50,
        blank=False,
        null=True,
        default='aucun'
    )

    def __str__(self):
        if self.etage.lower() == "rez-de-chaussée":
            return f"{self.nom} ({self.etage})"
        else:
            return f"{self.nom} ({self.etage} Étage)"

    def get_delete_url(self):
        return reverse('supprimer_salle', kwargs={'salle_id': self.id})


class Materiel(models.Model):
    nom = models.CharField(
        max_length=100,
        blank=False,
        null=True,
        default=''
    )
    budget = models.CharField(
        max_length=100,
        blank=False,
        null=True,
        default=''
    )
    proprietaire = models.ForeignKey(
        Enseignant,
        on_delete=models.CASCADE,
        null=True,
        related_name='materiels_possedes'
    )
    lieu = models.ForeignKey(
        Salle,
        on_delete=models.CASCADE,
        null=True
    )
    possesseur = models.ForeignKey(
        Enseignant,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='materiels_en_possession'
    )

    def __str__(self):
        return self.nom

    def get_accessoires_url(self):
        return reverse('liste_accessoires', args=[self.id])

    @classmethod
    def get_materiels_possedes(cls, enseignant):
        return cls.objects.filter(possesseur__icontains=f"{enseignant.nom} {enseignant.prenom}")

class TransfertMateriel(models.Model):
    material = models.ForeignKey(
        Materiel,
        on_delete=models.CASCADE,
        null=True
    )
    ancien_possesseur = models.ForeignKey(
        Enseignant,
        on_delete=models.CASCADE,
        null=True,
        related_name='transferts_sortants'
    )
    nouveau_possesseur = models.ForeignKey(
        Enseignant,
        on_delete=models.CASCADE,
        null=True,
        related_name='transferts_entrants'
    )
    date_transfert = models.DateField()
    ancien_lieu = models.ForeignKey(
        Salle,
        on_delete=models.CASCADE,
        related_name='transferts_sortants',
        null=True
    )
    nouveau_lieu = models.ForeignKey(
        Salle,
        on_delete=models.CASCADE,
        related_name='transferts_entrants',
        null=True
    )
    occasion = models.CharField(
        max_length=100
    )
    objectif = models.TextField()

    def __str__(self):
        return f"Transfert {self.material.nom} - {self.date_transfert}"

class AccessoireMateriel(models.Model):
    material = models.ForeignKey(
        Materiel,
        on_delete=models.CASCADE,
        null=True
    )
    nom = models.CharField(
        max_length=100,
        blank = True
    )
    present = models.BooleanField(
        default=True
    )
    etat = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )

class TransfertAccessoire(models.Model):
    transfert = models.ForeignKey(
        TransfertMateriel,
        on_delete=models.CASCADE
    )
    accessoire = models.ForeignKey(
        AccessoireMateriel,
        on_delete=models.CASCADE
    )
    ancienne_presence = models.BooleanField(
        default=True
    )
    nouvelle_presence = models.BooleanField(
        default=True
    )
    ancien_etat = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )
    nouveau_etat = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )

    def __str__(self):
        return f"Transfert {self.transfert.material.nom} - Accessoire {self.accessoire.nom}"

gestion_materiel/views.py
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from .models import Enseignant, Materiel, AccessoireMateriel, TransfertMateriel, Salle, TransfertAccessoire
from .forms import EnseignantForm, SalleForm, AccessoireViaMaterielForm, MaterielForm, AccessoireFormSet, TransfertForm
from django.contrib import messages

def accueil(request):
    return render(request, 'gestion_materiel/accueil.html')

"""enseignants"""
def liste_enseignants(request):
    enseignants = Enseignant.objects.all()
    return render(request, 'gestion_materiel/enseignants/liste_enseignants.html', {'enseignants': enseignants})

def ajout_enseignant(request):
    if request.method == 'POST':
        form = EnseignantForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Enseignant ajouté avec succès')
            return redirect('liste_enseignants')
    else:
        form = EnseignantForm()
    return render(request, 'gestion_materiel/enseignants/ajout_enseignant.html', {'form': form})


def liste_materiels_possedes(request, enseignant_id):
    enseignant = Enseignant.objects.get(id=enseignant_id)

    materiels = Materiel.objects.filter(Q(possesseur__nom__icontains=enseignant.nom) & Q(possesseur__prenom__icontains=enseignant.prenom))

    context = {
        'enseignants': enseignant,
        'materiels': materiels,
    }

    return render(request, 'gestion_materiel/enseignants/liste_materiels_possedes.html', context)


def liste_materiels_proprietaire(request, enseignant_id):
    enseignant = Enseignant.objects.get(id=enseignant_id)

    materiels = Materiel.objects.filter(Q(proprietaire__nom__icontains=enseignant.nom) & Q(proprietaire__prenom__icontains=enseignant.prenom))

    context = {
        'enseignants': enseignant,
        'materiels': materiels,
    }

    return render(request, 'gestion_materiel/enseignants/liste_materiels_proprietaire.html', context)

def supprimer_enseignant(request, enseignant_id):
    if request.method == 'POST':
        enseignant = Enseignant.objects.get(id=enseignant_id)
        enseignant.delete()
        messages.add_message(request, messages.SUCCESS, "L'enseignants a été supprimé avec succès", extra_tags='danger')
    return redirect('liste_enseignants')

"""salles"""
def liste_salles(request):
    salles = Salle.objects.all()
    return render(request, 'gestion_materiel/salles/liste_salles.html', {'salles': salles})

def liste_materiels_salle(request, salle_id):
    salle = get_object_or_404(Salle, id=salle_id)
    materiels = Materiel.objects.filter(lieu=salle)
    return render(request, 'gestion_materiel/salles/liste_materiels_salle.html', {'salles': salle, 'materiels': materiels})

def ajout_salle(request):
    if request.method == 'POST':
        form = SalleForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Salle ajoutée avec succès')
            return redirect('liste_salles')
    else:
        form = SalleForm()
    return render(request, 'gestion_materiel/salles/ajout_salle.html', {'form': form})

def supprimer_salle(request, salle_id):
    salle = get_object_or_404(Salle, id=salle_id)
    salle.delete()
    messages.add_message(request, messages.SUCCESS, "La salles a été supprimée avec succès", extra_tags='danger')
    return redirect('liste_salles')


"""materiel"""
def liste_materiels(request):
    materiels = Materiel.objects.all()
    return render(request, 'gestion_materiel/materiel/liste_materiels.html', {'materiels': materiels})

def supprimer_materiel(request, materiel_id):
    materiel = get_object_or_404(Materiel, id=materiel_id)
    materiel.delete()
    messages.add_message(request, messages.SUCCESS, "Le matériel a été supprimé avec succès", extra_tags='danger')
    return redirect('liste_materiels')

def ajout_materiel(request):
    if request.method == 'POST':
        materiel_form = MaterielForm(request.POST)
        accessoire_formset = AccessoireFormSet(request.POST, prefix='accessoires')
        if materiel_form.is_valid() and accessoire_formset.is_valid():
            materiel = materiel_form.save()
            salle, created = Salle.objects.get_or_create(nom="001", etage="rez-de-chaussée")
            materiel.lieu = salle
            materiel.save()
            for form in accessoire_formset:
                if form.is_valid() and form.cleaned_data.get('nom'):
                    accessoire = form.save(commit=False)
                    accessoire.material = materiel
                    accessoire.save()
            messages.success(request, 'Matériel ajouté avec succès')
            return redirect('liste_materiels')
    else:
        materiel_form = MaterielForm()
        accessoire_formset = AccessoireFormSet(prefix='accessoires')

    return render(request, 'gestion_materiel/materiel/ajout_materiel.html',
                  {'materiel_form': materiel_form, 'accessoire_formset': accessoire_formset})


"""accessoire"""
def liste_accessoires(request, materiel_id):
    materiel = Materiel.objects.get(id=materiel_id)
    accessoires = AccessoireMateriel.objects.filter(material=materiel)
    return render(request, 'gestion_materiel/materiel/accessoire/liste_accessoires.html', {'materiel': materiel, 'accessoires': accessoires})

def supprimer_accessoire(request, materiel_id, accessoire_id):
    accessoire = get_object_or_404(AccessoireMateriel, id=accessoire_id)
    accessoire.delete()
    messages.add_message(request, messages.SUCCESS, "L'accessoire a été supprimé avec succès", extra_tags='danger')
    return redirect('liste_accessoires', materiel_id=materiel_id)

def modifier_accessoire(request, materiel_id, accessoire_id):
    accessoire = get_object_or_404(AccessoireMateriel, id=accessoire_id)
    materiel = Materiel.objects.get(id=materiel_id)
    if request.method == 'POST':
        form = AccessoireViaMaterielForm(request.POST, instance=accessoire)
        if form.is_valid():
            form.save()
            messages.success(request, 'Accessoire modifié avec succès')
            return redirect('liste_accessoires', materiel_id=materiel_id)
    else:
        form = AccessoireViaMaterielForm(instance=accessoire)

    return render(request, 'gestion_materiel/materiel/accessoire/modifier_accessoire.html', {'form': form, 'materiel': materiel})

def ajouter_accessoire_via_materiel(request, materiel_id):
    materiel = get_object_or_404(Materiel, id=materiel_id)

    if request.method == 'POST':
        form = AccessoireViaMaterielForm(request.POST)
        if form.is_valid():
            accessoire = form.save(commit=False)
            accessoire.material = materiel
            accessoire.save()
            messages.success(request, 'Accessoire ajouté avec succès')
            return redirect('liste_accessoires', materiel_id=materiel.id)
    else:
        form = AccessoireViaMaterielForm()

    return render(request, 'gestion_materiel/materiel/accessoire/ajout_accessoire_via_materiel.html', {'materiel': materiel, 'form': form})

"""transfert"""
from django.shortcuts import render, redirect
from gestion_materiel.models import Materiel

def choix_materiel(request):
    if request.method == 'POST':
        action = request.POST.get('action', '')
        if action == 'historique':
            materiel_id = request.POST.get('materiel', '')
            return redirect('liste_historique_transferts', materiel_id=materiel_id)
        elif action == 'creation':
            materiel_id = request.POST.get('materiel', '')
            return redirect('ajout_transfert', materiel_id=materiel_id)

    materiels = Materiel.objects.all()
    selected_materiel_id = request.session.get('selected_materiel_id', None)

    return render(request, 'gestion_materiel/transfert/choix_materiel.html', {
        'materiels': materiels,
        'selected_materiel_id': selected_materiel_id,
    })

def ajout_transfert(request, materiel_id):
    materiel = Materiel.objects.get(id=materiel_id)
    accessoires = materiel.accessoiremateriel_set.all()

    enseignants = Enseignant.objects.all()
    salles = Salle.objects.all()

    if request.method == 'POST':
        form = TransfertForm(request.POST)
        if form.is_valid():

            transfert = form.save(commit=False)
            transfert.material = materiel
            transfert.ancien_possesseur = materiel.possesseur
            transfert.ancien_lieu = materiel.lieu

            salle_id = form.cleaned_data['nouveau_lieu'].id
            salle = Salle.objects.get(id=salle_id)

            if request.POST.get('rendre') == 'Oui':
                materiel.possesseur = None
                transfert.nouveau_possesseur = None
                materiel.lieu = Salle.objects.get(nom="001", etage="rez-de-chaussée")
            else:
                materiel.possesseur = transfert.nouveau_possesseur
                materiel.lieu = salle

            materiel.save()
            transfert.save()

            for accessoire in accessoires:
                present_key = 'present_' + str(accessoire.id)
                etat_key = 'etat_' + str(accessoire.id)

                present_value = request.POST.get(present_key)
                if present_value == "Oui":
                    nouvelle_presence = True
                    nouvel_etat = request.POST.get(etat_key, accessoire.etat)
                else:
                    nouvelle_presence = False
                    nouvel_etat = "Absent"

                TransfertAccessoire.objects.create(
                    transfert=transfert,
                    accessoire=accessoire,
                    ancienne_presence=accessoire.present,
                    nouvelle_presence=nouvelle_presence,
                    ancien_etat=accessoire.etat,
                    nouveau_etat=nouvel_etat
                )

                accessoire.present = nouvelle_presence
                accessoire.etat = nouvel_etat
                accessoire.save()

gestion_materiel/templates/gestion_materiel/enseignants/ajout_enseignant.html
<!DOCTYPE html>
<html>
<head>
    <title>Ajout d'enseignant</title>
</head>
<body>
    {% include 'gestion_materiel/includes/entete.html' %}

    <div class="container">
        <h1>Ajouter un enseignant</h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_nom">Nom :</label>
                <input type="text" class="form-control" id="id_nom" name="nom" required>
            </div>
            <div class="form-group">
                <label for="id_prenom">Prénom :</label>
                <input type="text" class="form-control" id="id_prenom" name="prenom" required>
            </div>
            <button type="submit" class="btn btn-primary">Ajouter</button>
        </form>
    </div>
</body>
</html>

gestion_materiel/templates/gestion_materiel/enseignants/liste_enseignants.html
<!DOCTYPE html>
<html>
<head>
    <title>Liste des enseignants</title>
</head>
<body>
    {% include 'gestion_materiel/includes/entete.html' %}

    <div class="container">
        <h1>Liste des enseignants</h1>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Supprimer</th>
                    <th>Actions</th>  <!-- Nouvelle colonne pour les boutons d'actions -->
                </tr>
            </thead>
            <tbody>
                {% for enseignant in enseignants %}
                    <tr>
                        <td>{{ enseignant.nom }}</td>
                        <td>{{ enseignant.prenom }}</td>
                        <td>
                            <form method="post" action="{% url 'supprimer_enseignant' enseignant.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Supprimer</button>
                            </form>
                        </td>
                        <td>
                            <a href="{% url 'liste_materiels_possedes' enseignant.id %}" class="btn btn-primary">Matériels Possédés</a>
                            <a href="{% url 'liste_materiels_proprietaire' enseignant.id %}" class="btn btn-success">Matériels Propriétaires</a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4">Aucun enseignant trouvé.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

gestion_materiel/templates/gestion_materiel/enseignants/liste_materiels_possedes.html
<!DOCTYPE html>
<html>
<head>
    <title>Matériels de {{ enseignant.nom }} {{ enseignant.prenom }}</title>
</head>
<body>
    {% include 'gestion_materiel/includes/entete.html' %}

    <div class="container">
        <h1>Liste des matériels possédés par {{ enseignant.nom }} {{ enseignant.prenom }}</h1>
        <a href="{% url 'liste_enseignants'%}" class="btn btn-primary">Liste des enseignants</a>
        <div style="margin-top: 10px;"></div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nom du matériel</th>
                    <th>Lieu</th>
                </tr>
            </thead>
            <tbody>
                {% for materiel in materiels %}
                    <tr>
                        <td>{{ materiel.nom }}</td>
                        <td>{{ materiel.lieu }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="2">Aucun matériel trouvé.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

gestion_materiel/templates/gestion_materiel/enseignants/liste_materiels_proprietaire.html
<!DOCTYPE html>
<html>
<head>
    <title>Matériels dont {{ enseignant.nom }} {{ enseignant.prenom }} est propriétaire</title>
</head>
<body>
    {% include 'gestion_materiel/includes/entete.html' %}

    <div class="container">
        <h1>Liste des matériels dont {{ enseignant.nom }} {{ enseignant.prenom }} est propriétaire</h1>
        <a href="{% url 'liste_enseignants'%}" class="btn btn-primary">Liste des enseignants</a>
        <div style="margin-top: 10px;"></div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nom du matériel</th>
                    <th>Lieu</th>
                </tr>
            </thead>
            <tbody>
                {% for materiel in materiels %}
                    <tr>
                        <td>{{ materiel.nom }}</td>
                        <td>{{ materiel.lieu }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="2">Aucun matériel trouvé.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>