django_bluzat/urls.py
from django.contrib import admin
from django.urls import path

from gestion_materiel import views
from gestion_materiel.views import accueil, liste_enseignants, ajout_enseignant, liste_salles, liste_accessoires, ajout_salle, liste_materiels

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accueil', accueil, name='accueil'),

    path('enseignants/liste_enseignants', liste_enseignants, name='liste_enseignants'),
    path('enseignants/ajout_enseignant', ajout_enseignant, name='ajout_enseignant'),
    path('enseignants/<int:enseignant_id>/supprimer', views.supprimer_enseignant, name='supprimer_enseignant'),
    path('enseignants/<int:enseignant_id>/materiels_possedes/', views.liste_materiels_possedes, name='liste_materiels_possedes'),
    path('enseignants/<int:enseignant_id>/materiels_proprietaire/', views.liste_materiels_proprietaire, name='liste_materiels_proprietaire'),

    path('salles/liste_salles', liste_salles, name='liste_salles'),
    path('liste_materiels_salle/<int:salle_id>/', views.liste_materiels_salle, name='liste_materiels_salle'),
    path('salles/ajout_salle', ajout_salle, name='ajout_salle'),
    path('salles/supprimer/<int:salle_id>/', views.supprimer_salle, name='supprimer_salle'),

    path('materiel/liste_materiels', liste_materiels, name='liste_materiels'),
    path('materiel/supprimer/<int:materiel_id>/', views.supprimer_materiel, name='supprimer_materiel'),
    path('materiel/ajout_materiel/', views.ajout_materiel, name='ajout_materiel'),

    path('materiel/<int:materiel_id>/accessoires/', liste_accessoires, name='liste_accessoires'),
    path('materiel/<int:materiel_id>/accessoires/supprimer/<int:accessoire_id>', views.supprimer_accessoire, name='supprimer_accessoire'),
    path('materiel/<int:materiel_id>/accessoires/ajouter/', views.ajouter_accessoire_via_materiel, name='ajouter_accessoire'),
    path('materiel/<int:materiel_id>/accessoire/<int:accessoire_id>/modifier/', views.modifier_accessoire, name='modifier_accessoire'),

    path('transfert/choix_materiel', views.choix_materiel, name='choix_materiel'),
    path('transfert/<int:materiel_id>/liste_historique_transferts/', views.liste_historique_transferts, name='liste_historique_transferts'),
    path('transfert/<int:materiel_id>/afficher_transfert/<int:transfert_id>/', views.afficher_transfert,name='afficher_transfert'),
    path('transfert/ajout_transfert/<int:materiel_id>/', views.ajout_transfert, name='ajout_transfert'),
    path('transfert/<int:materiel_id>/supprimer/<int:transfert_id>/', views.supprimer_transfert, name='supprimer_transfert'),
]

gestion_materiel/models.py
from django.db import models
from django.urls import reverse

class Enseignant(models.Model):
    nom = models.CharField(
        max_length=50,
        blank=False,
        null=True,
        default='aucun'
    )
    prenom = models.CharField(
        max_length=50,
        blank=False,
        null=True,
        default='aucun'
    )

    def __str__(self):
        return f"{self.nom} {self.prenom}"

class Salle(models.Model):
    nom = models.CharField(
        max_length=50,
        blank=False,
        null=True,
        default='aucun'
    )
    etage = models.CharField(
        max_length=50,
        blank=False,
        null=True,
        default='aucun'
    )

    def __str__(self):
        if self.etage.lower() == "rez-de-chaussée":
            return f"{self.nom} ({self.etage})"
        else:
            return f"{self.nom} ({self.etage} Étage)"

    def get_delete_url(self):
        return reverse('supprimer_salle', kwargs={'salle_id': self.id})


class Materiel(models.Model):
    nom = models.CharField(
        max_length=100,
        blank=False,
        null=True,
        default=''
    )
    budget = models.CharField(
        max_length=100,
        blank=False,
        null=True,
        default=''
    )
    proprietaire = models.ForeignKey(
        Enseignant,
        on_delete=models.CASCADE,
        null=True,
        related_name='materiels_possedes'
    )
    lieu = models.ForeignKey(
        Salle,
        on_delete=models.CASCADE,
        null=True
    )
    possesseur = models.ForeignKey(
        Enseignant,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='materiels_en_possession'
    )

    def __str__(self):
        return self.nom

    def get_accessoires_url(self):
        return reverse('liste_accessoires', args=[self.id])

    @classmethod
    def get_materiels_possedes(cls, enseignant):
        return cls.objects.filter(possesseur__icontains=f"{enseignant.nom} {enseignant.prenom}")

class TransfertMateriel(models.Model):
    material = models.ForeignKey(
        Materiel,
        on_delete=models.CASCADE,
        null=True
    )
    ancien_possesseur = models.ForeignKey(
        Enseignant,
        on_delete=models.CASCADE,
        null=True,
        related_name='transferts_sortants'
    )
    nouveau_possesseur = models.ForeignKey(
        Enseignant,
        on_delete=models.CASCADE,
        null=True,
        related_name='transferts_entrants'
    )
    date_transfert = models.DateField()
    ancien_lieu = models.ForeignKey(
        Salle,
        on_delete=models.CASCADE,
        related_name='transferts_sortants',
        null=True
    )
    nouveau_lieu = models.ForeignKey(
        Salle,
        on_delete=models.CASCADE,
        related_name='transferts_entrants',
        null=True
    )
    occasion = models.CharField(
        max_length=100
    )
    objectif = models.TextField()

    def __str__(self):
        return f"Transfert {self.material.nom} - {self.date_transfert}"

class AccessoireMateriel(models.Model):
    material = models.ForeignKey(
        Materiel,
        on_delete=models.CASCADE,
        null=True
    )
    nom = models.CharField(
        max_length=100,
        blank = True
    )
    present = models.BooleanField(
        default=True
    )
    etat = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )

class TransfertAccessoire(models.Model):
    transfert = models.ForeignKey(
        TransfertMateriel,
        on_delete=models.CASCADE
    )
    accessoire = models.ForeignKey(
        AccessoireMateriel,
        on_delete=models.CASCADE
    )
    ancienne_presence = models.BooleanField(
        default=True
    )
    nouvelle_presence = models.BooleanField(
        default=True
    )
    ancien_etat = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )
    nouveau_etat = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )

    def __str__(self):
        return f"Transfert {self.transfert.material.nom} - Accessoire {self.accessoire.nom}"

gestion_materiel/views.py
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from .models import Enseignant, Materiel, AccessoireMateriel, TransfertMateriel, Salle, TransfertAccessoire
from .forms import EnseignantForm, SalleForm, AccessoireViaMaterielForm, MaterielForm, AccessoireFormSet, TransfertForm
from django.contrib import messages

def accueil(request):
    return render(request, 'gestion_materiel/accueil.html')

"""enseignants"""
def liste_enseignants(request):
    enseignants = Enseignant.objects.all()
    return render(request, 'gestion_materiel/enseignants/liste_enseignants.html', {'enseignants': enseignants})

def ajout_enseignant(request):
    if request.method == 'POST':
        form = EnseignantForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Enseignant ajouté avec succès')
            return redirect('liste_enseignants')
    else:
        form = EnseignantForm()
    return render(request, 'gestion_materiel/enseignants/ajout_enseignant.html', {'form': form})


def liste_materiels_possedes(request, enseignant_id):
    enseignant = Enseignant.objects.get(id=enseignant_id)

    materiels = Materiel.objects.filter(Q(possesseur__nom__icontains=enseignant.nom) & Q(possesseur__prenom__icontains=enseignant.prenom))

    context = {
        'enseignants': enseignant,
        'materiels': materiels,
    }

    return render(request, 'gestion_materiel/enseignants/liste_materiels_possedes.html', context)


def liste_materiels_proprietaire(request, enseignant_id):
    enseignant = Enseignant.objects.get(id=enseignant_id)

    materiels = Materiel.objects.filter(Q(proprietaire__nom__icontains=enseignant.nom) & Q(proprietaire__prenom__icontains=enseignant.prenom))

    context = {
        'enseignants': enseignant,
        'materiels': materiels,
    }

    return render(request, 'gestion_materiel/enseignants/liste_materiels_proprietaire.html', context)

def supprimer_enseignant(request, enseignant_id):
    if request.method == 'POST':
        enseignant = Enseignant.objects.get(id=enseignant_id)
        enseignant.delete()
        messages.add_message(request, messages.SUCCESS, "L'enseignants a été supprimé avec succès", extra_tags='danger')
    return redirect('liste_enseignants')

"""salles"""
def liste_salles(request):
    salles = Salle.objects.all()
    return render(request, 'gestion_materiel/salles/liste_salles.html', {'salles': salles})

def liste_materiels_salle(request, salle_id):
    salle = get_object_or_404(Salle, id=salle_id)
    materiels = Materiel.objects.filter(lieu=salle)
    return render(request, 'gestion_materiel/salles/liste_materiels_salle.html', {'salles': salle, 'materiels': materiels})

def ajout_salle(request):
    if request.method == 'POST':
        form = SalleForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Salle ajoutée avec succès')
            return redirect('liste_salles')
    else:
        form = SalleForm()
    return render(request, 'gestion_materiel/salles/ajout_salle.html', {'form': form})

def supprimer_salle(request, salle_id):
    salle = get_object_or_404(Salle, id=salle_id)
    salle.delete()
    messages.add_message(request, messages.SUCCESS, "La salles a été supprimée avec succès", extra_tags='danger')
    return redirect('liste_salles')


"""materiel"""
def liste_materiels(request):
    materiels = Materiel.objects.all()
    return render(request, 'gestion_materiel/materiel/liste_materiels.html', {'materiels': materiels})

def supprimer_materiel(request, materiel_id):
    materiel = get_object_or_404(Materiel, id=materiel_id)
    materiel.delete()
    messages.add_message(request, messages.SUCCESS, "Le matériel a été supprimé avec succès", extra_tags='danger')
    return redirect('liste_materiels')

def ajout_materiel(request):
    if request.method == 'POST':
        materiel_form = MaterielForm(request.POST)
        accessoire_formset = AccessoireFormSet(request.POST, prefix='accessoires')
        if materiel_form.is_valid() and accessoire_formset.is_valid():
            materiel = materiel_form.save()
            salle, created = Salle.objects.get_or_create(nom="001", etage="rez-de-chaussée")
            materiel.lieu = salle
            materiel.save()
            for form in accessoire_formset:
                if form.is_valid() and form.cleaned_data.get('nom'):
                    accessoire = form.save(commit=False)
                    accessoire.material = materiel
                    accessoire.save()
            messages.success(request, 'Matériel ajouté avec succès')
            return redirect('liste_materiels')
    else:
        materiel_form = MaterielForm()
        accessoire_formset = AccessoireFormSet(prefix='accessoires')

    return render(request, 'gestion_materiel/materiel/ajout_materiel.html',
                  {'materiel_form': materiel_form, 'accessoire_formset': accessoire_formset})


"""accessoire"""
def liste_accessoires(request, materiel_id):
    materiel = Materiel.objects.get(id=materiel_id)
    accessoires = AccessoireMateriel.objects.filter(material=materiel)
    return render(request, 'gestion_materiel/materiel/accessoire/liste_accessoires.html', {'materiel': materiel, 'accessoires': accessoires})

def supprimer_accessoire(request, materiel_id, accessoire_id):
    accessoire = get_object_or_404(AccessoireMateriel, id=accessoire_id)
    accessoire.delete()
    messages.add_message(request, messages.SUCCESS, "L'accessoire a été supprimé avec succès", extra_tags='danger')
    return redirect('liste_accessoires', materiel_id=materiel_id)

def modifier_accessoire(request, materiel_id, accessoire_id):
    accessoire = get_object_or_404(AccessoireMateriel, id=accessoire_id)
    materiel = Materiel.objects.get(id=materiel_id)
    if request.method == 'POST':
        form = AccessoireViaMaterielForm(request.POST, instance=accessoire)
        if form.is_valid():
            form.save()
            messages.success(request, 'Accessoire modifié avec succès')
            return redirect('liste_accessoires', materiel_id=materiel_id)
    else:
        form = AccessoireViaMaterielForm(instance=accessoire)

    return render(request, 'gestion_materiel/materiel/accessoire/modifier_accessoire.html', {'form': form, 'materiel': materiel})

def ajouter_accessoire_via_materiel(request, materiel_id):
    materiel = get_object_or_404(Materiel, id=materiel_id)

    if request.method == 'POST':
        form = AccessoireViaMaterielForm(request.POST)
        if form.is_valid():
            accessoire = form.save(commit=False)
            accessoire.material = materiel
            accessoire.save()
            messages.success(request, 'Accessoire ajouté avec succès')
            return redirect('liste_accessoires', materiel_id=materiel.id)
    else:
        form = AccessoireViaMaterielForm()

    return render(request, 'gestion_materiel/materiel/accessoire/ajout_accessoire_via_materiel.html', {'materiel': materiel, 'form': form})

"""transfert"""
from django.shortcuts import render, redirect
from gestion_materiel.models import Materiel

def choix_materiel(request):
    if request.method == 'POST':
        action = request.POST.get('action', '')
        if action == 'historique':
            materiel_id = request.POST.get('materiel', '')
            return redirect('liste_historique_transferts', materiel_id=materiel_id)
        elif action == 'creation':
            materiel_id = request.POST.get('materiel', '')
            return redirect('ajout_transfert', materiel_id=materiel_id)

    materiels = Materiel.objects.all()
    selected_materiel_id = request.session.get('selected_materiel_id', None)

    return render(request, 'gestion_materiel/transfert/choix_materiel.html', {
        'materiels': materiels,
        'selected_materiel_id': selected_materiel_id,
    })

def ajout_transfert(request, materiel_id):
    materiel = Materiel.objects.get(id=materiel_id)
    accessoires = materiel.accessoiremateriel_set.all()

    enseignants = Enseignant.objects.all()
    salles = Salle.objects.all()

    if request.method == 'POST':
        form = TransfertForm(request.POST)
        if form.is_valid():

            transfert = form.save(commit=False)
            transfert.material = materiel
            transfert.ancien_possesseur = materiel.possesseur
            transfert.ancien_lieu = materiel.lieu

            salle_id = form.cleaned_data['nouveau_lieu'].id
            salle = Salle.objects.get(id=salle_id)

            if request.POST.get('rendre') == 'Oui':
                materiel.possesseur = None
                transfert.nouveau_possesseur = None
                materiel.lieu = Salle.objects.get(nom="001", etage="rez-de-chaussée")
            else:
                materiel.possesseur = transfert.nouveau_possesseur
                materiel.lieu = salle

            materiel.save()
            transfert.save()

            for accessoire in accessoires:
                present_key = 'present_' + str(accessoire.id)
                etat_key = 'etat_' + str(accessoire.id)

                present_value = request.POST.get(present_key)
                if present_value == "Oui":
                    nouvelle_presence = True
                    nouvel_etat = request.POST.get(etat_key, accessoire.etat)
                else:
                    nouvelle_presence = False
                    nouvel_etat = "Absent"

                TransfertAccessoire.objects.create(
                    transfert=transfert,
                    accessoire=accessoire,
                    ancienne_presence=accessoire.present,
                    nouvelle_presence=nouvelle_presence,
                    ancien_etat=accessoire.etat,
                    nouveau_etat=nouvel_etat
                )

                accessoire.present = nouvelle_presence
                accessoire.etat = nouvel_etat
                accessoire.save()

gestion_materiel/templates/gestion_materiel/transfert/afficher_transfert.html
<!DOCTYPE html>
<html>
<head>
    <title>Transfert - {{ transfert.material.nom }}</title>
</head>
<body>
    {% include 'gestion_materiel/includes/entete.html' %}

    <div class="container">
        <h1>Détails du transfert - {{ transfert.material.nom }}</h1>
        <a href="{% url 'liste_historique_transferts' materiel_id=transfert.material.id %}" class="btn btn-primary">Liste des historiques des transferts</a>
        <div style="margin-top: 10px;"></div>

        <p><strong>Nom du matériel :</strong> {{ transfert.material.nom }}</p>
        <p><strong>Date du transfert :</strong> {{ transfert.date_transfert }}</p>
        <p><strong>Objectif :</strong> {{ transfert.objectif }}</p>
        <p><strong>Occasion :</strong> {{ transfert.occasion }}</p>
        <p><strong>Possesseur précédent :</strong> {{ transfert.ancien_possesseur }}</p>
        <p><strong>Nouveau possesseur :</strong> {{ transfert.nouveau_possesseur }}</p>
        <p><strong>Lieu précédent :</strong> {{ transfert.ancien_lieu }}</p>
        <p><strong>Nouveau lieu :</strong> {{ transfert.nouveau_lieu }}</p>

        <h2>Accessoires</h2>
       <table class="table table-striped">
            <tr>
                <th>Nom</th>
                <th>Ancienne présence</th>
                <th>Nouvelle présence</th>
                <th>Ancien état</th>
                <th>Nouvel état</th>
            </tr>
            {% for accessoire in transfert.transfertaccessoire_set.all %}
                <tr>
                    <td>{{ accessoire.accessoire.nom }}</td>
                    <td>{% if accessoire.ancienne_presence %}Oui{% else %}Non{% endif %}</td>
                    <td>{% if accessoire.nouvelle_presence %}Oui{% else %}Non{% endif %}</td>
                    <td>{{ accessoire.ancien_etat }}</td>
                    <td>{{ accessoire.nouveau_etat }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="5">Il n'y a pas d'accessoire associé.</td>
                </tr>
            {% endfor %}
        </table>
    </div>
</body>
</html>

gestion_materiel/templates/gestion_materiel/transfert/ajout_transfert.html
<!DOCTYPE html>
<html>
<head>
    <title>Créer un transfert</title>
</head>
<body>
    {% include 'gestion_materiel/includes/entete.html' %}

    <div class="container">
        <h1>Créer un transfert pour {{ materiel.nom }}</h1>
        <div class="container text-center">
            <a href="{% url 'choix_materiel' %}" class="btn btn-primary">Choix du matériel</a>
        </div>
        <div style="margin-top: 10px;"></div>
        <form method="post">
            {% csrf_token %}
            <!--info générales-->
            <h2 style="text-align: center;">Informations actuelles</h2>
            <div class="form-group">
                <label style="font-weight: bold;">Matériel :</label>
                <input type="text" class="form-control" value="{{ materiel.nom }}" readonly>
            </div>
            <div class="form-group">
                <label style="font-weight: bold;">Possesseur actuel :</label>
                <input type="text" class="form-control" value="{{ materiel.possesseur }}" readonly>
            </div>
            <div class="form-group">
                <label style="font-weight: bold;">Lieu actuel :</label>
                <input type="text" class="form-control" value="{{ materiel.lieu }}" readonly>
            </div>

            <!--Liste des accessoires actuels-->
            {% for accessoire in accessoires %}
                <div class="form-group">
                    <label style="font-weight: bold;">Nom de l'accessoire :</label>
                    <input type="text" class="form-control" value="{{ accessoire.nom }}" readonly>
                </div>
                <div class="form-group">
                    <label>Présent :</label>
                    {% if accessoire.present %}
                        <input type="text" class="form-control" value="Oui" readonly>
                    {% else %}
                        <input type="text" class="form-control" value="Non" readonly>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label>État :</label>
                    <input type="text" class="form-control" value="{{ accessoire.etat }}" readonly>
                </div>
            {% endfor %}

            <h2 style="text-align: center;">Informations à remplir</h2>
            <!-- Nouvelles infos-->

            <div class="form-group">
                <label style="font-weight: bold;">Rendre :</label>
                <select class="form-control" name="rendre" id="id_rendre" onchange="updateFields()">
                    <option value="Oui">Oui</option>
                    <option value="Non" selected>Non</option>
                </select>
            </div>

           <div class="form-group">
                <label style="font-weight: bold;">Nouveau possesseur (Ne pas prendre en compte si le matériel est rendu):</label>
                <select class="form-control" name="nouveau_possesseur">
                    {% for enseignant in enseignants %}
                        <option value="{{ enseignant.id }}">
                            {{ enseignant.nom }} {{ enseignant.prenom }}
                        </option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
                <label style="font-weight: bold;">Lieu de transfert (Ne pas prendre en compte si le matériel est rendu):</label>
                <select class="form-control" name="nouveau_lieu">
                    {% for salle in salles %}
                        <option value="{{ salle.id }}">
                            {{ salle.nom }} {{ salle.etage }}
                        </option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
                <label style="font-weight: bold;">Date transfert :</label>
                <input type="date" class="form-control" name="date_transfert">
            </div>

            <!--Nouvelles infos accessoires-->
            {% for accessoire in accessoires %}
                <div class="form-group">
                    <label style="font-weight: bold;">Nom de l'accessoire :</label>
                    <input type="text" class="form-control" value="{{ accessoire.nom }}" readonly>
                </div>
                <div class="form-group">
                    <label>Présent :</label>
                    <select class="form-control" name="present_{{ accessoire.id }}">
                        <option value="Oui" {% if accessoire.present == "Oui" %}selected{% endif %}>Oui</option>
                        <option value="Non" {% if accessoire.present == "Non" %}selected{% endif %}>Non</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>État (Ne pas prendre en compte si absent):</label>
                    <select class="form-control" name="etat_{{ accessoire.id }}">
                        <option value="Fonctionnel" {% if accessoire.etat == "Fonctionnel" %}selected{% endif %}>Fonctionnel</option>
                        <option value="Défaillant" {% if accessoire.etat == "Défaillant" %}selected{% endif %}>Défaillant</option>
                        <option value="Non fonctionnel" {% if accessoire.etat == "Non fonctionnel" %}selected{% endif %}>Non fonctionnel</option>
                    </select>
                </div>
            {% endfor %}

            <div class="form-group">
                <label style="font-weight: bold;">Occasion :</label>
                <input type="text" class="form-control" name="occasion">
            </div>

            <div class="form-group">
                <label style="font-weight: bold;">Objectif :</label>
                <textarea class="form-control" name="objectif" rows="3"></textarea>
            </div>

            <button type="submit" class="btn btn-primary">Enregistrer</button>
        </form>
    </div>
</body>
</html>

gestion_materiel/templates/gestion_materiel/transfert/choix_materiel.html
<!DOCTYPE html>
<html>
<head>
    <title>Transfer</title>
</head>
<body>
    {% include 'gestion_materiel/includes/entete.html' %}

    <div class="container">
        <h1>Choisir un matériel à transférer</h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_materiel">Sélectionner un matériel :</label>
                <select class="form-control" id="id_materiel" name="materiel" required>
                    <option value="" selected disabled>Choisir un matériel</option>
                    {% for materiel in materiels %}
                        <option value="{{ materiel.id }}" {% if materiel.id == selected_materiel_id %}selected{% endif %}>{{ materiel.nom }}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" name="action" value="historique" class="btn btn-primary">Historique des transferts</button>
            <button type="submit" name="action" value="creation" class="btn btn-primary">Créer un transfert</button>
        </form>
    </div>
</body>
</html>

gestion_materiel/templates/gestion_materiel/transfert/liste_historique_transferts.html
<!DOCTYPE html>
<html>
<head>
    <title>Historique des Transferts</title>
</head>
<body>
    {% include 'gestion_materiel/includes/entete.html' %}

    <div class="container">
        <h1>Historique des Transferts pour {{ materiel.nom }}</h1>
        <a href="{% url 'choix_materiel'%}" class="btn btn-primary">Choix du matériel</a>
        <div style="margin-top: 10px;"></div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Ancien Possesseur</th>
                    <th>Nouveau Possesseur</th>
                    <th>Détails du transfert</th>
                    <th>Supprimer</th>
                </tr>
            </thead>
            <tbody>
                {% for transfert in transferts %}
                    <tr>
                        <td>{{ transfert.date_transfert }}</td>
                        <td>{{ transfert.ancien_possesseur }}</td>
                        <td>{{ transfert.nouveau_possesseur }}</td>
                        <td><a href="{% url 'afficher_transfert' materiel_id=materiel.id transfert_id=transfert.id %}" class="btn btn-primary">Détails</a></td>
                        <td><a href="{% url 'supprimer_transfert' materiel_id=materiel.id transfert_id=transfert.id %}" class="btn btn-danger">Supprimer</a></td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="5">Aucun transfert trouvé.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>